name: API Test

on:
  workflow_dispatch:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Run Newman Action
      - name: Run API tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman_collection.json
          environment: postman_env.json
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
