name: API Test

on:
  workflow_dispatch:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2: Put client secret in postman env file
      - name: Prepare test environment file
        run: |
          sed "s/{{POST_ID}}/${{ secrets.POST_ID }}/g" postman_env.json > env_with_secrets.json

      # Step 3: Run Newman Action
      - name: Run API tests
        uses: matt-ball/newman-action@master
        with:
          collection: postman_collection.json
          environment: env_with_secrets.json
          apiKey: ${{ secrets.POSTMAN_API_KEY }}
